[project]
name = "lem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dtaidistance>=2.4.0",
    "matplotlib>=3.10.8",
    "minisom>=2.3.6",
    "pandas>=3.0.2",
    "pyarrow>=23.0.1",
    "pydash>=8.0.6",
    "pymannkendall>=1.4.3",
    "requests>=2.33.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "statsmodels>=0.14.6"
]

[dependency-groups]
dev = [
    "nbconvert>=7.17.1",
    "ruff>=0.15.11",
    "ruff>=0.15.11",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "jupytext>=1.19.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I"]
